spring:
  datasource:
    url: jdbc:postgresql://172.20.0.5:5432/postgres?stringtype=unspecified
    username: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.yaml
    default-schema: public
    liquibase-schema: public

logging:
  level:
    liquibase: INFO